#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: /logout

contacts:
  path: /contacts
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: front/contacts.html.twig